#forcing a new build
substitutions:
  _AR_REGION: asia-south1
  _RUN_REGION: asia-south1
  _REPOSITORY: news-tts
  _SERVICE: news-tts

timeout: 3600s 

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build CPU image'
  args:
  - build
  - '--cache-from'
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'
  - '-t'
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'
  - '.'
  timeout: 2400s

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image'
  args:
  - push
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'
  timeout: 600s

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run (CPU)'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud run deploy $_SERVICE \
      --image "$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest" \
      --region "$_RUN_REGION" \
      --allow-unauthenticated \
      --concurrency=4 \
      --timeout=1800 \
      --memory=16Gi \
      --cpu=4 \
      --min-instances=0 \
      --max-instances=4 \
      --set-secrets=MONGO_URI=MONGO_URI:latest \
      --set-secrets=DATABASE_NAME=DATABASE_NAME:latest \
      --set-secrets=FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET:latest \
      --set-secrets=ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest \
      --set-secrets=ELEVENLABS_VOICE_ID=ELEVENLABS_VOICE_ID:latest \
      --set-secrets=FIREBASE_SERVICE_ACCOUNT_BASE64=FIREBASE_SERVICE_ACCOUNT_BASE64:latest \
      --set-env-vars=HF_HOME=/app/.cache/huggingface,HF_HUB_CACHE=/app/.cache/huggingface/hub,TRANSFORMERS_CACHE=/app/.cache/huggingface/transformers,HF_HUB_OFFLINE=1,TRUST_REMOTE_CODE=1,TRANSLATION_PER_CALL_TIMEOUT=90,TRANSLATION_PER_CALL_TIMEOUT_RETRY=120
  timeout: 600s

images:
- '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'