substitutions:
  _AR_REGION: asia-south1
  _RUN_REGION: asia-south1
  _REPOSITORY: news-tts
  _SERVICE: news-tts

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8 
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build CPU image'
  args:
  - build
  - '-t'
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image'
  args:
  - push
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run (CPU)'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud run deploy $_SERVICE \
      --image "$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest" \
      --region "$_RUN_REGION" \
      --allow-unauthenticated \
      --concurrency=1 \
      --timeout=1800 \
      --memory=4Gi \
      --cpu=1 \
      --min-instances=0 \
      --max-instances=2 \
      --set-secrets=MONGO_URI=MONGO_URI:latest \
      --set-secrets=DATABASE_NAME=DATABASE_NAME:latest \
      --set-secrets=FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET:latest \
      --set-secrets=ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest \
      --set-env-vars=HF_HOME=/app/.cache/huggingface,HF_HUB_CACHE=/app/.cache/huggingface/hub,TRANSFORMERS_CACHE=/app/.cache/huggingface/transformers,TRANSLATION_PER_CALL_TIMEOUT=90,TRANSLATION_PER_CALL_TIMEOUT_RETRY=120 \
      --set-secrets=FIREBASE_SERVICE_ACCOUNT_BASE64=FIREBASE_SERVICE_ACCOUNT_BASE64:latest


- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Allow unauthenticated invoke'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud beta run services add-iam-policy-binding $_SERVICE \
      --region "$_RUN_REGION" \
      --member="allUsers" \
      --role="roles/run.invoker"

images:
- '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'