substitutions:
  _AR_REGION: asia-south1
  _RUN_REGION: asia-south1
  _REPOSITORY: news-tts
  _SERVICE: news-tts

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build CPU image'
  args:
  - build
  - '-t'
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image'
  args:
  - push
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run (CPU)'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud run deploy $_SERVICE \
      --image "$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest" \
      --region "$_RUN_REGION" \
      --allow-unauthenticated \
      --concurrency=1 \
      --timeout=900 \
      --memory=8Gi \
      --cpu=4 \
      --min-instances=0 \
      --max-instances=1 \
      --set-secrets=MONGO_URI=projects/$PROJECT_ID/secrets/MONGO_URI:latest \
      --set-secrets=DATABASE_NAME=projects/$PROJECT_ID/secrets/DATABASE_NAME:latest \
      --set-secrets=FIREBASE_STORAGE_BUCKET=projects/$PROJECT_ID/secrets/FIREBASE_STORAGE_BUCKET:latest \
      --set-secrets=ELEVENLABS_API_KEY=projects/$PROJECT_ID/secrets/ELEVENLABS_API_KEY:latest

images:
- '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'