substitutions:
  _AR_REGION: asia-south1
  _RUN_REGION: asia-southeast1
  _REPOSITORY: news-tts
  _SERVICE: news-tts

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build GPU image'
  args:
  - build
  - '-f'
  - 'Dockerfile.gpu'
  - '-t'
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$SHORT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image'
  args:
  - push
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run (GPU) with secrets'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud run deploy $_SERVICE \
      --image "$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$SHORT_SHA" \
      --region "$_RUN_REGION" \
      --execution-environment=gen2 \
      --allow-unauthenticated \
      --concurrency=1 \
      --timeout=900 \
      --memory=32Gi \
      --cpu=8 \
      --min-instances=1 \
      --max-instances=1 \
      --gpu=1 \
      --gpu-type=nvidia-l4 \
      --set-secrets=AI4BHARAT_MODELS_PATH=AI4BHARAT_MODELS_PATH:latest,CLOUD_PROVIDER=CLOUD_PROVIDER:latest,CORS_ORIGINS=CORS_ORIGINS:latest,DATABASE_NAME=DATABASE_NAME:latest,FIREBASE_SERVICE_ACCOUNT_BASE64=FIREBASE_SERVICE_ACCOUNT_BASE64:latest,FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET:latest,HF_HOME=HF_HOME:latest,HF_HUB_OFFLINE=HF_HUB_OFFLINE:latest,LOG_LEVEL=LOG_LEVEL:latest,MODEL_LOCAL_EN_INDIC=MODEL_LOCAL_EN_INDIC:latest,MODEL_LOCAL_INDIC_EN=MODEL_LOCAL_INDIC_EN:latest,MODEL_SIZE=MODEL_SIZE:latest,MONGO_URI=MONGO_URI:latest,TRANSFORMERS_CACHE=TRANSFORMERS_CACHE:latest,TRANSFORMERS_OFFLINE=TRANSFORMERS_OFFLINE:latest,ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest

images:
- '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$SHORT_SHA'