substitutions:
  _AR_REGION: asia-south1
  _RUN_REGION: asia-south1
  _REPOSITORY: news-tts
  _SERVICE: news-tts

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build CPU image'
  args:
  - build
  - '-t'
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image'
  args:
  - push
  - '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run (CPU)'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud run deploy $_SERVICE \
      --image "$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest" \
      --region "$_RUN_REGION" \
      --allow-unauthenticated \
      --concurrency=1 \
      --timeout=1200 \
      --memory=4Gi \
      --cpu=2 \
      --min-instances=0 \
      --max-instances=1 \
      --set-secrets=MONGO_URI=MONGO_URI:latest \
      --set-secrets=DATABASE_NAME=DATABASE_NAME:latest \
      --set-secrets=FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET:latest \
      --set-secrets=ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest
      --set-env-vars=TRANSFORMERS_CACHE=/app/.cache/huggingface/transformers \
      --set-env-vars=LOG_LEVEL=INFO \
      --set-secrets=FIREBASE_SERVICE_ACCOUNT_BASE64=FIREBASE_SERVICE_ACCOUNT_BASE64:latest

images:
- '$_AR_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest'