name: news-tts-endpoint
type: managed
auth_mode: key
description: "News TTS API with IndicTrans2 1B models"
traffic_allocation:
  - traffic_percentage: 100
    deployment: news-tts-v1
deployments:
  - name: news-tts-v1
    model: null  # No model, just container deployment
    environment:
      dockerfile_path: Dockerfile
      build_context: . 
      ports:
        - port: 8080
    resources:
      cpu: 2
      memory: 14Gi
    scaling:
      min_instances: 1
      max_instances: 3
      target_utilization_percent: 70
    liveness_probe:
      failure_threshold: 30
      period_seconds: 10
      timeout_seconds: 2
      success_threshold: 1
      initial_delay_seconds: 30
      path: /health
      port: 8080
    readiness_probe:
      failure_threshold: 10
      period_seconds: 5
      timeout_seconds: 2
      success_threshold: 1
      initial_delay_seconds: 10
      path: /health
      port: 8080
